name: webservant
description: A simple Dart Webserver library for small REST Services
version: 0.0.1
author: Konstantin Ullrich <konstantinullrich12@gmail.com>
homepage: https://github.com/konstantinullrich
repository: https://github.com/konstantinullrich/webservant
issue_tracker: https://github.com/konstantinullrich/webservant/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
